# Generated by Django 3.0.5 on 2023-01-29 19:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('MN', 'Men'), ('WM', 'Women'), ('UN', 'Unisex'), ('KD', 'Kids')], max_length=11)),
                ('category2', multiselectfield.db.fields.MultiSelectField(choices=[('UW', 'Underwear'), ('JK', 'Jacket'), ('ST', 'Suit'), ('TR', 'Trouser'), ('SH', 'Shirt'), ('SN', 'Sneakers'), ('PJ', 'Pyjamas'), ('SE', 'Shoe'), ('JN', 'Jean'), ('SR', 'Short'), ('HD', 'Hoodie')], max_length=3)),
            ],
        ),
    ]
