# Generated by Django 3.0.5 on 2023-01-30 12:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_auto_20230129_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MN', 'Men'), ('WM', 'Women'), ('UN', 'Unisex'), ('KD', 'Kids'), ('UW', 'Underwear'), ('GW', 'Gowns'), ('ST', 'Suits'), ('TR', 'Trousers'), ('SH', 'Shirts'), ('FW', 'Footwears'), ('PJ', 'Pyjamas'), ('SK', 'Skirts'), ('JN', 'Jeans'), ('SR', 'Shorts'), ('HD', 'Hoodies')], max_length=3),
        ),
    ]
